# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wordWGT.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 376)
        Form.setMinimumSize(QtCore.QSize(0, 200))
        Form.setMaximumSize(QtCore.QSize(16777215, 400))
        Form.setStyleSheet("#Form{\n"
"border-radius: 10px;\n"
"     border: 2px solid;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-bottom: 8;\n"
"border-radius: 10px;\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 10px;\n"
"")
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.changeBtn = QtWidgets.QPushButton(Form)
        self.changeBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"")
        self.changeBtn.setObjectName("changeBtn")
        self.horizontalLayout.addWidget(self.changeBtn)
        self.deleteBtn = QtWidgets.QPushButton(Form)
        self.deleteBtn.setMaximumSize(QtCore.QSize(100, 30))
        self.deleteBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout.addWidget(self.deleteBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.changeBtn.setText(_translate("Form", "Изменить"))
        self.deleteBtn.setText(_translate("Form", "X"))
